### ISSUE TITLE
Remove reference to arm_v5t_le- from Makefile

### ISSUE THREAD

**Issue by pfalcon** [projectgus/kernel_wm8505#2]
There's leftover from upstream vendor:

CROSS_COMPILE ?= arm_v5t_le-

arm_v5t_le- should be removed from there, leaving in pristine state. Otherwise, it produces confusing output:

<pre>
 $ make via_obj
 make: arm_v5t_le-gcc: Command not found
 cp -Rf ./via_obj.arm_v5t-2629.01/* ./
</pre>

**Comment by projectgus** [comment]
Done
