### ISSUE TITLE
Setting KERNELRELEASE

### ISSUE THREAD

**Issue by ffxx68** [projectgus/kernel_wm8505#4]
After trying your latest build procedure (as per
https://github.com/projectgus/kernel_wm8505#readme), I tried to use a
newly compiled wmt_battery.ko in my netbook, but:

 insmod /.driver/wmt_battery.ko

failed (because of an error message that I miss now).

It worked (and I could see my own debugging messages, with "dmesg")
only after I recompiled the module setting "KERNELRELEASE" at command
line. I.e.

 make modules_install ARCH=arm INSTALL_MOD_PATH=./modules/staging
KERNELRELEASE=2.6.29-00236-g4f8dbbb-dirty

Indeed, "strings wmt_battery.ko | grep vermagic" didn't return the
content of KERNELRELEASE (as it should) if I used the "export
KERNELRELEASE=..." mode. I always used "export CROSS_COMPILE=arm-
eabi-" instead.

**Comment by ffxx68** [comment]
For completeness, the error message was:

 # insmod ./wmt_battery.ko

insmod: init_module './wmt_battery.ko' failed (Exec format error)

**Comment by projectgus** [comment]
Updated README.

(The only issue was that the README implied KERNELRELEASE could be set as an environment variable ,turns out it must be set as a make variable override - ie via command line, as per the existing example.)
